backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/img'

collections:
  - name: 'Pages'
    label: 'Pages'
    files:
      - label: 'About page'
        name: 'about'
        file: 'index.md'
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Subtitle'
            name: 'subtitle'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
      - label: 'Consultancy page',
        name: 'consultancy'
        file: '_pages/consultancy.md'
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Subtitle'
            name: 'subtitle'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
      - label: 'Teaching page',
        name: 'teaching'
        file: '_pages/teaching.md'
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Subtitle'
            name: 'subtitle'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'

  - name: 'Content'
    label: 'Content'
    files:
      - label: 'Publications'
        name: 'Publications'
        file: '_data/publications.yml'
        fields:
          - label: 'Publications'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Content', name: 'content', widget: 'string' }
      - label: 'Awards'
        name: 'Awards'
        file: '_data/awards.yml'
        fields:
          - label: 'Awards'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Content', name: 'content', widget: 'string' }
      - label: 'Book Reviews'
        name: 'Book Reviews'
        file: '_data/book-reviews.yml'
        fields:
          - label: 'Book reviews'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Content', name: 'content', widget: 'string' }
      - label: 'Books'
        name: 'Books'
        file: '_data/books.yml'
        fields:
          - label: 'Books'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Content', name: 'content', widget: 'string' }
      - label: 'Chapters'
        name: 'Chapters'
        file: '_data/chapters.yml'
        fields:
          - label: 'Chapters'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Content', name: 'content', widget: 'string' }
      - label: 'Conferences'
        name: 'Conferences'
        file: '_data/conferences.yml'
        fields:
          - label: 'Conferences'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Authors', name: 'authors', widget: 'string' }
              - { label: 'Year', name: 'year', widget: 'string' }
              - { label: 'Content', name: 'content', widget: 'string' }
              - { label: 'Conference', name: 'conference', widget: 'string' }
              - { label: 'Location', name: 'location', widget: 'string' }
              - { label: 'Date', name: 'date', widget: 'string' }
      - label: 'Esteem Measures'
        name: 'Esteem Measures'
        file: '_data/esteem-measures.yml'
        fields:
          - label: 'Esteem Measures'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Content', name: 'content', widget: 'string' }
      - label: 'Scholarships'
        name: 'Scholarships'
        file: '_data/scholarships.yml'
        fields:
          - label: 'Scholarships'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Content', name: 'content', widget: 'string' }
      - label: 'Under Review'
        name: 'Under Review'
        file: '_data/under-review.yml'
        fields:
          - label: 'Under Review'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Content', name: 'content', widget: 'string' }
      - label: 'Esteem Service Leadership'
        name: 'Esteem Service Leadership'
        file: '_data/leadership.yml'
        fields:
          - label: 'Leadership'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Content', name: 'content', widget: 'string' }
      - label: 'Esteem Service Peer Review'
        name: 'Esteem Service Peer Review'
        file: '_data/peer-review.yml'
        fields:
          - label: 'Peer Review'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Content', name: 'content', widget: 'string' }
